version: '3'

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      dockerfile: python.Dockerfile
    restart: always
    # python unbuffered fixed lagging output to the console
    environment:
      PYTHONUNBUFFERED: 0
    working_dir: /usr/src/djangoapp
    ports:
      - "8000"
    volumes:
      - /djangoapp:/usr/src/djangoapp
    networks:
      - mynetwork
    command: "gunicorn --bind 0:8000 project.wsgi:application"
  nginx: 
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8080:8080"
    networks: 
      - mynetwork
networks:
  mynetwork:
